---

- name: Add authorized keys
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
  loop:
    - msuchy
    - mfabik

- name: Enable EPEL
  dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
    disable_gpg_check: yes
    state: present

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest


