---

- name: Add authorized keys
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
  loop:
    - msuchy
    - mfabik

- name: Check if epel-release is installed
  command:
    argv:
      - rpm 
      - -q 
      - epel-release
    warn: false
  ignore_errors: True
  register: rpm_check
  changed_when: "'is not installed' in rpm_check.stdout"

- name: Enable EPEL
  dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
    disable_gpg_check: yes
    state: present
  when: rpm_check.stdout.find('is not installed') != -1

- name: Enable powertools
  command:
    cmd: "dnf config-manager --set-enabled powertools"
    warn: false

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive
