---

- name: Add authorized keys
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
  loop:
    - msuchy
    - mfabik

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest


